name: shell commands

on:
  - push


jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: set terraform
        uses: hashicop/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init   
      - name: Multi line string
        run: |
          pwd
          node -v
          ls -a  